title: "Kode With Klossy Curriculum"
description: "Curriculum for the Kode With Klossy's 2021 Virtual camps."
url: "https://kode-with-klossy-camps.github.io/kwk-virtual-curriculum"

baseurl: ''
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME'
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

assets:
  root_url: '/kwk-virtual-curriculum/assets'

images:
  root_url: '/kwk-virtual-curriculum/assets/images'

plugins:
  - jemoji
